# Generated by Django 5.0.4 on 2026-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_exercise_video_url_state_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_area',
            field=models.CharField(choices=[('Legs', 'Legs'), ('Knee', 'Knee'), ('Hips', 'Hips'), ('Shoulder', 'Shoulder'), ('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back'), ('Core', 'Core'), ('Neck', 'Neck'), ('Ankle', 'Ankle'), ('Other', 'Other')], max_length=20),
        ),
    ]
